apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world

spec:
  replicas: 5 
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: strm/helloworld-http
        ports: 
        - containerPort: 80
